# Person CRUD

create_person:
    path: /api/v1/person
    methods: [POST]
    controller: App\Bundle\Basics\Crud\Controller\PersonCrudController::create

get_person:
    path: /api/v1/person/{id}
    methods: [GET]
    controller: App\Bundle\Basics\Crud\Controller\PersonCrudController::get

update_person:
    path: /api/v1/person/{id}
    methods: [PATCH]
    controller: App\Bundle\Basics\Crud\Controller\PersonCrudController::update

delete_person:
    path: /api/v1/person/{id}
    methods: [DELETE]
    controller: App\Bundle\Basics\Crud\Controller\PersonCrudController::delete

# Article CRUD

create_article:
    path: /api/v1/article
    methods: [POST]
    controller: App\Bundle\Basics\Crud\Controller\ArticleCrudController::create
