index:
    path: /
    controller: App\Basics\Routing\Controller\BaseRoutingController::index

basic_routing_routes:
    resource: '@BasicsRoutingBundle/Resources/config/routing.yml'

basic_crud_routes:
    resource: '@BasicsCrudBundle/Resources/config/routing.yml'


