index:
    path: /
    controller: App\Basics\Routing\Controller\BaseRoutingController::index

route1:
    path: /route1/{param1}
    controller: App\Basics\Routing\Controller\BaseRoutingController::route1
