route1:
    path: /route1/{param1}
    controller: App\Basics\Routing\Controller\BaseRoutingController::route1

route2:
    path: /route2
    controller: App\Basics\Routing\Controller\BaseRoutingController::route2

route3:
    path: /route3
    controller: App\Basics\Routing\Controller\BaseRoutingController::route3